"""Render the canonical submission numbers from the shipped router artifact.

The report body and `docs/SUBMISSION.md` must quote the same figures as the
artifact that is actually submitted. This script simulates the public set with
`artifacts/geometric_router.json` (not a freshly refit router) and emits both a
JSON summary and a markdown block, so the documents can be refreshed from one
source instead of being edited by hand.

Usage:
    python scripts/render_submission_numbers.py
    python scripts/render_submission_numbers.py --write_markdown docs/report_assets/submission_numbers.md
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

from router_impls.geometric.router import GeometricRouter  # noqa: E402
from router_impls.geometric.simulator import simulate_public_set  # noqa: E402
from router_impls.geometric.tuning import score_tier_summary  # noqa: E402

TIER_ORDER = ("fast", "balanced", "premium")


def build_submission_numbers(
    artifact_path: str | Path,
    train_path: str | Path,
    specs_path: str | Path,
    latency_summary_path: str | Path,
) -> dict:
    router = GeometricRouter.load(artifact_path)
    train_df = pd.read_csv(train_path)
    specs_df = pd.read_csv(specs_path) if Path(specs_path).exists() else pd.DataFrame()
    payload = simulate_public_set(router, train_df, specs_df, tiers=TIER_ORDER)
    tier_summary = payload["summary"]["tier_summary"]
    latency = _load_latency(latency_summary_path)

    tiers = []
    overall = 0.0
    for tier in TIER_ORDER:
        summary = tier_summary[tier]
        score = score_tier_summary(summary, tier)
        overall += float(score["weighted_score"])
        tiers.append(
            {
                "tier": tier,
                "count": int(summary["count"]),
                "budget_limit": float(summary["budget_limit"]),
                "mean_quality": float(summary["mean_quality"]),
                "mean_cost": float(summary["mean_cost"]),
                "cost_over_limit": int(summary["cost_over_limit"]),
                "under_route": int(summary["under_route"]),
                "over_route": int(summary["over_route"]),
                "weighted_score": float(score["weighted_score"]),
                "tier_weight": float(score["tier_weight"]),
                "latency_ms_mean": latency.get(tier, {}).get("latency_ms_mean"),
                "latency_ms_p95": latency.get(tier, {}).get("latency_ms_p95"),
            }
        )

    return {
        "artifact": str(artifact_path),
        "train_path": str(train_path),
        "overall_weighted_score": overall,
        "tiers": tiers,
    }


def _load_latency(path: str | Path) -> dict[str, dict[str, float]]:
    latency_path = Path(path)
    if not latency_path.exists():
        return {}
    df = pd.read_csv(latency_path)
    if "budget_tier" not in df.columns:
        return {}
    return {str(row["budget_tier"]): dict(row) for _, row in df.iterrows()}


def render_markdown(numbers: dict) -> str:
    lines = [
        "<!-- generated by scripts/render_submission_numbers.py - do not edit by hand -->",
        "",
        f"최신 public evaluation 기준 (artifact: `{numbers['artifact']}`)",
        "",
        f"- Overall weighted score: `{numbers['overall_weighted_score']:.3f}`",
        "",
        "| Tier | count | budget | mean_quality | mean_cost | cost_over_limit | under_route | weighted_score | latency_mean |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in numbers["tiers"]:
        latency = row["latency_ms_mean"]
        latency_text = "-" if latency is None else f"{float(latency):.2f}ms"
        lines.append(
            f"| {row['tier'].capitalize()} | {row['count']} | {row['budget_limit']:.2f} | "
            f"{row['mean_quality']:.3f} | {row['mean_cost']:.3f} | "
            f"{row['cost_over_limit']}/{row['count']} | {row['under_route']}/{row['count']} | "
            f"{row['weighted_score']:.3f} | {latency_text} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifact", default="artifacts/geometric_router.json")
    parser.add_argument("--train_path", default="data/public/example_train.csv")
    parser.add_argument("--specs_path", default="data/public/example_eval_specs.csv")
    parser.add_argument("--latency_summary", default="docs/report_assets/latency_summary.csv")
    parser.add_argument("--output", default="docs/report_assets/submission_numbers.json")
    parser.add_argument("--write_markdown", default="docs/report_assets/submission_numbers.md")
    args = parser.parse_args()

    numbers = build_submission_numbers(
        args.artifact,
        args.train_path,
        args.specs_path,
        args.latency_summary,
    )
    markdown = render_markdown(numbers)

    if args.output:
        output = Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(numbers, ensure_ascii=False, indent=2), encoding="utf-8")
    if args.write_markdown:
        markdown_path = Path(args.write_markdown)
        markdown_path.parent.mkdir(parents=True, exist_ok=True)
        markdown_path.write_text(markdown, encoding="utf-8")

    print(markdown)


if __name__ == "__main__":
    main()
